services:
    database:
      image: mysql:8
      container_name: mysql
      environment:
        - MYSQL_DATABASE=superheroes
        - MYSQL_USER=sa
        - MYSQL_PASSWORD=admin
      volumes: 
        - database:/var/lib/mysql
      networks:
        - network
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        interval: 10s
        timeout: 3s
        retries: 3
    back:
      build: 
        context: java/
        dockerfile: Dockerfile
      image: back-ds
      container_name: back-ds
      ports:
        - 8448:8448
      environment:
        - spring.datasource.url=jdbc:mysql://mysql:3306/superheroes
        - spring.datasource.username=sa
        - spring.datasource.password=admin
      networks:
        - network
      healthcheck:
        test: curl http://localhost:8448/actuator/health
        interval: 5s
        timeout: 3s
        retries: 3
      depends_on: 
        database:
          condition: service_healthy
          restart: true
    front:
      build: 
        context: angular/
        dockerfile: Dockerfile
      image: front
      container_name: front
      ports:
        - 8888:80
      environment:
        - BACKEND_URL=http://localhost:8448
      depends_on: 
        back:
          condition: service_healthy
          restart: true

volumes:
  database:

networks:
  network:

  