name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/polytech2024
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./java/
        file: Dockerfile.gha
        push: true
        tags: rg.fr-par.scw.cloud/exampolytech2024/java:ayoub
    - name: Use CLI
      uses: scaleway/action-scw@v0
      id: cli
      with:
        version: v2.13.0
        access-key: ${{ secrets.SCW_ACCESS_KEY }}
        secret-key: ${{ secrets.SCW_SECRET_KEY }}
        default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        args: container container create name=ayoub-back namespace-id=4f8c01c3-6c86-4cba-abf7-a652eeaa04be registry-image=rg.fr-par.scw.cloud/exampolytech2024/java:ayoub min-scale=1 max-scale=1 memory-limit=512 cpu-limit=280 environment-variables.spring.datasource.url=jdbc:mysql://51.159.112.97:3306/etudiant4