name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 10
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/exampolytech2024
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.gha
        push: true
        tags: rg.fr-par.scw.cloud/exampolytech2024/angular:ayoub
    
